server:
  servlet:
    context-path: /
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nb666
    username: root
    password: 1234
    

mybatis-plus:
  type-aliases-package: com.cxxj.model
  mapper-locations: classpath:/mybatis/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
